// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0NyqTqZQJ6RQb6NFPfFEvF8I5xRokadA',
    appId: '1:583026412903:web:fa6421964c0d465c9df3c2',
    messagingSenderId: '583026412903',
    projectId: 'fix-me-app-d8065',
    authDomain: 'fix-me-app-d8065.firebaseapp.com',
    storageBucket: 'fix-me-app-d8065.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUvGfEMeTd60HKY-7ldSJEdU6cD36qbV0',
    appId: '1:583026412903:android:b8c907cb5a3439339df3c2',
    messagingSenderId: '583026412903',
    projectId: 'fix-me-app-d8065',
    storageBucket: 'fix-me-app-d8065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYmN94Y5mhh7JU0hgVlcqoHmlwfkVyo_s',
    appId: '1:583026412903:ios:f8cad36ae638c2f19df3c2',
    messagingSenderId: '583026412903',
    projectId: 'fix-me-app-d8065',
    storageBucket: 'fix-me-app-d8065.appspot.com',
    iosBundleId: 'com.example.fixMeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYmN94Y5mhh7JU0hgVlcqoHmlwfkVyo_s',
    appId: '1:583026412903:ios:e259ebe29631fda19df3c2',
    messagingSenderId: '583026412903',
    projectId: 'fix-me-app-d8065',
    storageBucket: 'fix-me-app-d8065.appspot.com',
    iosBundleId: 'com.example.fixMeApp.RunnerTests',
  );
}
